k8s:
  namespace: tekton-tasks
  serviceAccountName: tekton-sa
git:
  username: exampleUsername
  password: setInGitHubSecrets
  email: example@example.com
project:
  repository: https://github.com/Acuity-Inc/techchallenge-template-java-api-template.git
  branch: main
  dockerfile: Dockerfile
  source: src
  fetchSubmodules: false
  commitsToFetch: 1
  preCleanDir: true
  imageName: acuityinc/techchallenge-template-java-api-template
  projectName: tsg-innolab-app
