k8s:
  namespace: tekton-tasks
  serviceAccountName: tekton-sa
git:
  username: ${{ secrets.GIT_USERNAME }}
  password: ${{ secrets.GIT_PASSWORD }}
  email: ${{ secrets.GIT_EMAIL }}
project:
  repository: https://github.com/Acuity-Inc/techchallenge-template-java-api-template.git
  branch: main
  dockerfile: Dockerfile
  source: src
  fetchSubmodules: false
  commitsToFetch: 1
  preCleanDir: true
  imageName: acuityinc/techchallenge-template-java-api-template
  projectName: tsg-innolab-app
