apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-using-kubectl
  namespace: {{ (datasource "config").k8s.namespace }}
spec:
  workspaces:
    - name: output
      description: The git repo
  params:
    - name: pathToYamlFile
      default: gomplate-final/manifest.yaml
      description: The path to the yaml file to deploy within the git source
    - name: imageUrl
      description: Image name including repository
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;__IMAGE__;$(params.imageUrl);g"
        - "$(workspaces.output.path)/$(params.pathToYamlFile)"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(workspaces.output.path)/$(params.pathToYamlFile)"
