on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  pipeline-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # - uses: actions-hub/kubectl@master
      #   env:
      #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Install gomplate
        run: |
          curl -o /usr/local/bin/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/v3.11.6/gomplate_linux-amd64-slim
          chmod 755 /usr/local/bin/gomplate

      - name: Execute gomplate
        run: gomplate --input-dir=tekton/ --output-dir=gomplate-final/ --datasource config=tekton/config.yaml

      # - uses: actions-hub/kubectl@master
      #   with:
      #     args: apply -f ./gomplate-final/git-clone.yaml

      # - name: Define Git Clone Task
      #   uses: kodermax/kubectl-aws-eks@main
      #   env:
      #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      #   with:
      #     args: apply -f ./gomplate-final/git-clone.yaml

      # - name: Define Git Clone Task
      #   uses: steebchen/kubectl@v2.0.0
      #   with: # defaults to latest kubectl binary version
      #     config: ${{ secrets.KUBE_CONFIG_DATA }}
      #     command: apply -f ./gomplate-final/git-clone.yaml

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name "acuity-nonprod" --region "us-east-2"

      - name: Define Git Clone Task
        run: KUBECONFIG=/home/runner/.kube/config kubectl apply -f ./gomplate-final/git-clone.yaml

      # - uses: actions-hub/kubectl@master
      #   with:
      #     args: apply -f ./gomplate-final/docker-build.yaml

      - name: Define Docker Build Task
        uses: kodermax/kubectl-aws-eks@main
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f ./gomplate-final/docker-build.yaml

      # - uses: actions-hub/kubectl@master
      #   with:
      #     args: apply -f ./gomplate-final/kubectl-deploy.yaml

      - name: Define Kubectl Deploy Task
        uses: kodermax/kubectl-aws-eks@main
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f ./gomplate-final/kubectl-deploy.yaml

      # - uses: actions-hub/kubectl@master
      #   with:
      #     args: apply -f ./gomplate-final/pipeline.yaml

      - name: Define Pipeline
        uses: kodermax/kubectl-aws-eks@main
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f ./gomplate-final/pipeline.yaml

      # - uses: actions-hub/kubectl@master
      #   with:
      #     args: apply -f ./gomplate-final/pipeline-run.yaml

      - name: Define PipelineRun
        uses: kodermax/kubectl-aws-eks@main
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f ./gomplate-final/pipeline-run.yaml
