on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  pipeline-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      - name: Install gomplate
        run: |
          curl -o /usr/local/bin/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/v3.11.6/gomplate_linux-amd64-slim
          chmod 755 /usr/local/bin/gomplate
      - name: Execute gomplate
        run: gomplate --input-dir=tekton/ --output-dir=gomplate-final/ --datasource config=tekton/config.yaml
      - name: Read gomplate substitutions
        run: cat gomplate-final/*
      - uses: actions-hub/kubectl@master
        with:
          args: apply -f ./gomplate-final/git-clone.yaml
      - uses: actions-hub/kubectl@master
        with:
          args: apply -f ./gomplate-final/docker-build.yaml
      - uses: actions-hub/kubectl@master
        with:
          args: apply -f ./gomplate-final/kubectl-deploy.yaml
      - uses: actions-hub/kubectl@master
        with:
          args: apply -f ./gomplate-final/pipeline.yaml
      - uses: actions-hub/kubectl@master
        with:
          args: apply -f ./gomplate-final/pipeline-run.yaml
