on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  push:
    branches:
      - 'main'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 5 * * *'
jobs:
  integrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -o /usr/local/bin/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/v3.11.5/gomplate_linux-amd64
          chmod 755 /usr/local/bin/gomplate
          chmod 755 ./scripts/*.sh
          ./scripts/generate_codebase.sh

      - name: Set up Java Corretto 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Run checkstyle
        run: mvn checkstyle:checkstyle

      - name: Run unit tests
        run: mvn test

      - name: SonarQube scan
        run: mvn sonar:sonar -Dsonar.projectKey=${{ github.event.repository.name }} -Dsonar.projectName=${{ github.event.repository.name }} -Dsonar.login=${{ vars.TSG_INNOLAB_SONARQUBE_USER }} -Dsonar.password=${{ secrets.TSG_INNOLAB_SONARQUBE_PASSWORD }} -Dsonar.host.url=${{ vars.TSG_INNOLAB_SONARQUBE_URL }} -Dsonar.qualitygate.wait=true

      - name: Vulnerability scan
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b .
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b .
          ./syft . -o cyclonedx-xml > sbom.xml
          ./grype sbom.xml --fail-on critical

  create-ticket:
    runs-on: ubuntu-latest
    needs: [integrate] # Depends on integrate job above
    if: always() && needs.integrate.result == 'failure' && github.event_name != 'pull_request'

    steps:
      - name: Log in to JIRA
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ vars.TSG_INNOLAB_JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ vars.TSG_INNOLAB_JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.TSG_INNOLAB_JIRA_API_TOKEN }}

      - name: Create JIRA Issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: IL23
          issuetype: Task
          summary: CI Failure for ${{ github.repository }}
          description: Please see full details at https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id }}
          fields: '{"labels": ["TechChallengeSuccess"]}'

      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created, see ${{ vars.TSG_INNOLAB_JIRA_BASE_URL }}/browse/${{ steps.create.outputs.issue }}"

  pipeline-deploy:
    runs-on: ubuntu-latest
    needs: [create-ticket]
    steps:
      - name: Install gomplate
        run: |
          curl -o /usr/local/bin/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/v3.11.6/gomplate_linux-amd64-slim
          chmod 755 /usr/local/bin/gomplate
          gomplate --help